"""add title to chat session

Revision ID: 93e6a7ac414a
Revises: 6b4f34dc7cf6
Create Date: 2026-03-09 21:37:04.592099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '93e6a7ac414a'
down_revision: Union[str, None] = '6b4f34dc7cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatsession', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatsession', 'title')
    # ### end Alembic commands ###
